#!/bin/bash

if [ -z "$MINIO_ACCESS_KEY" ] || [ -z "$MINIO_SECRET_KEY" ] || [ -z "$MINIO_HOST" ] ; then
  echo "envars MINIO_ACCESSS_KEY=$MINIO_ACCESS_KEY, MINIO_SECRET_KEY=$MINIO_SECRET_KEY, MINIO_HOST=$MINIO_HOST undefined STOP"
  exit 1
fi


if [ -z "$MINIO_ACCESS_KEY_REMOTE" ] || [ -z "$MINIO_SECRET_KEY_REMOTE" ] || [ -z "$MINIO_HOST_REMOTE" ] ; then
  echo "envars MINIO_ACCESS_KEY_REMOTE=$MINIO_ACCESS_KEY_REMOTE, MINIO_SECRET_KEY_REMOTE=$MINIO_SECRET_KEY_REMOTE, MINIO_HOST_REMOTE=$MINIO_HOST_REMOTE STOP"
  exit 1
fi

MC=./mc

ACCESS_KEY=$MINIO_ACCESS_KEY
SECRET_KEY=$MINIO_SECRET_KEY
HOST="http://${MINIO_HOST}:9000"

CMD="$MC config host add minio $HOST $ACCESS_KEY $SECRET_KEY"
echo $CMD
eval $CMD



ACCESS_KEY_2=$MINIO_ACCESS_KEY_REMOTE
SECRET_KEY_2=$MINIO_SECRET_KEY_REMOTE
HOST_2="http://${MINIO_HOST_REMOTE}:9000"

CMD="$MC config host add minio-remote $HOST_2 $ACCESS_KEY_2 $SECRET_KEY_2"
echo $CMD
eval $CMD

$MC mb minio2/f18.db
$MC mb minio2/test

echo "mirroring remote: $MINIO_HOST_REMOTE -> local: $MINIO_HOST"
$MC mirror minio-remote minio
